pipeline {
    agent any
    
    stages {
        stage('Build') {
        steps {
            // Get some code from a GitHub repository
            git 'https://github.com/alvarosjf/maven-app.git'
            
            // Run Maven on a Unix agent.
            def mvnHome = tool name: 'Maven', type: 'maven'
            sh "${mvnHome}/bin/mvn -version"
        }
        steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
